import type { Metadata } from "next";
import Link from "next/link";
import { ChevronRight, Shield } from "lucide-react";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import { SITE_URL } from "@/lib/siteConfig";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "Read the GetAhead AI Privacy Policy to understand what data we collect, how we use it, how we protect it, and your rights as a user.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "Privacy policy — GetAhead AI",
    description: "Our privacy policy explains how we collect, use, and protect your data.",
    url: "/privacy",
    type: "website",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "GetAhead" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy policy — GetAhead AI",
    description: "Our privacy policy explains how we collect, use, and protect your data.",
    images: ["/og-image.png"],
  },
};

const EFFECTIVE_DATE = "17 July 2026";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-paper">
      {/* Navbar */}
      <SiteHeader />

      {/* Hero */}
      <section className="pt-32 pb-12 bg-paper">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="inline-flex items-center gap-2 bg-blue-100 text-blue-700 text-sm font-semibold px-4 py-1.5 rounded-full mb-6">
            <Shield className="w-4 h-4" />
            Your privacy matters
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>
            Privacy policy
          </h1>
          <p className="text-graphite mb-3">
            Effective date: <strong>{EFFECTIVE_DATE}</strong>
          </p>
          <p className="text-graphite leading-relaxed">
            GetAhead AI (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is committed to protecting your privacy. This policy explains what personal data we collect, why we collect it, how we use it, and what rights you have over your data. Please read it carefully.
          </p>
        </div>
      </section>

      {/* TOC */}
      <section className="py-8 border-b border-rule">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-sm font-semibold text-graphite uppercase tracking-wide mb-4">Contents</h2>
          <div className="grid sm:grid-cols-2 gap-2 text-sm">
            {[
              "1. Information We Collect",
              "2. Why We Collect It",
              "3. How We Use Your Data",
              "4. AI Processing",
              "5. Cookies",
              "6. Authentication & Sessions",
              "7. Data Sharing",
              "8. Data Retention",
              "9. Your Rights",
              "10. Data Security",
              "11. Children",
              "12. Changes to This Policy",
              "13. Contact Us",
            ].map((item) => (
              <a key={item} href={`#section-${item.split(".")[0].trim()}`} className="flex items-center gap-1.5 text-graphite hover:text-blue-600 transition-colors">
                <ChevronRight className="w-3.5 h-3.5 text-gray-400" />
                {item}
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* Policy Content */}
      <article className="py-12 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="prose prose-gray max-w-none space-y-10">

          <section id="section-1">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>1. Information We Collect</h2>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">a) Account Information</h3>
            <p className="text-ink leading-relaxed mb-4">When you create an account, we collect: your full name, email address, hashed password (we never store plain-text passwords), and your selected role (Student, Teacher, or Institution).</p>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">b) Evaluation Data</h3>
            <p className="text-ink leading-relaxed mb-4">When you upload an answer sheet and run an evaluation, we store: the metadata of the upload (subject, grade, exam type, filename), the text extracted from your answer sheet by OCR, the marks and feedback generated by the AI, and the timestamps of the evaluation.</p>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">c) Question Papers</h3>
            <p className="text-ink leading-relaxed mb-4">If you generate a question paper, we store: the parameters you selected (subject, grade, difficulty, total marks) and the generated paper content.</p>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">d) Usage Data</h3>
            <p className="text-ink leading-relaxed mb-4">We collect technical usage data including: browser type, operating system, IP address (for security and rate limiting), and timestamps of key actions (login, upload, evaluation).</p>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">e) Audit Logs</h3>
            <p className="text-ink leading-relaxed">For security and operational purposes, we maintain audit logs of significant actions (e.g., admin logins, account deletions). These logs include IP addresses and action timestamps.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-2">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>2. Why We Collect It</h2>
            <ul className="space-y-3 text-ink">
              {[
                { label: "Account data", reason: "To create and manage your account, authenticate you, and allow you to access your evaluations." },
                { label: "Evaluation data", reason: "To process your answer sheets, display your results, and power the Analytics dashboard." },
                { label: "Question paper data", reason: "To save generated papers to your account for future reference." },
                { label: "Usage data", reason: "To monitor platform performance, detect abuse, enforce rate limits, and debug technical issues." },
                { label: "Audit logs", reason: "To maintain security, investigate incidents, and comply with our internal governance standards." },
              ].map((item) => (
                <li key={item.label} className="flex gap-3">
                  <span className="font-semibold text-gray-900 min-w-[160px]">{item.label}:</span>
                  <span>{item.reason}</span>
                </li>
              ))}
            </ul>
          </section>

          <hr className="border-rule" />

          <section id="section-3">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>3. How We Use Your Data</h2>
            <p className="text-ink leading-relaxed mb-4">We use your data solely to provide and improve the GetAhead AI service. Specifically:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li>To authenticate you and maintain your session</li>
              <li>To process uploaded answer sheets through OCR and AI evaluation</li>
              <li>To display evaluation results, marks breakdowns, and AI feedback in your dashboard</li>
              <li>To generate performance analytics from your evaluation history</li>
              <li>To generate question papers based on your parameters</li>
              <li>To send transactional emails (password reset, support ticket notifications)</li>
              <li>To detect and prevent abuse, fraud, and security threats</li>
            </ul>
            <p className="text-ink leading-relaxed mt-4">We do <strong>not</strong> use your data to serve advertisements, profile you for marketing, or sell your data to third parties.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-4">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>4. AI Processing</h2>
            <p className="text-ink leading-relaxed mb-4">GetAhead AI uses the Google Gemini API to evaluate answer sheets and generate question papers. When you submit an evaluation:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li>The OCR-extracted text from your answer sheet is sent to the Gemini API as part of a structured prompt.</li>
              <li>The response (marks and feedback) is received and stored in your account.</li>
              <li>We retain the OCR-extracted text from your answer sheet in GetAhead AI&apos;s own database, alongside the marks and feedback, so your evaluation report remains available in your dashboard.</li>
            </ul>
            <p className="text-ink leading-relaxed mt-4">Please refer to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Google&apos;s Privacy Policy</a> and the <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Gemini API Terms of Service</a> for details on how Google handles API request data. We do not use your data to train our own AI models.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-5">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>5. Cookies</h2>
            <p className="text-ink leading-relaxed mb-4">GetAhead AI uses the following cookies:</p>
            <div className="overflow-x-auto">
              <table className="w-full text-sm border border-rule rounded-xl overflow-hidden">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="text-left px-4 py-3 font-semibold text-ink">Cookie</th>
                    <th className="text-left px-4 py-3 font-semibold text-ink">Purpose</th>
                    <th className="text-left px-4 py-3 font-semibold text-ink">Duration</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-rule">
                  {[
                    { name: "next-auth.session-token", purpose: "Authenticates your session, including admin access where applicable. HttpOnly, Secure, SameSite=Lax.", duration: "15 minutes, refreshed while active" },
                    { name: "next-auth.csrf-token", purpose: "Protects against CSRF attacks on authentication forms.", duration: "Session" },
                  ].map((row) => (
                    <tr key={row.name} className="bg-surface">
                      <td className="px-4 py-3 font-mono text-xs text-ink">{row.name}</td>
                      <td className="px-4 py-3 text-graphite">{row.purpose}</td>
                      <td className="px-4 py-3 text-graphite whitespace-nowrap">{row.duration}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <p className="text-ink leading-relaxed mt-4">We do not use advertising cookies, third-party tracking cookies, or analytics cookies. All cookies are strictly necessary for the platform to function.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>6. Authentication &amp; Sessions</h2>
            <p className="text-ink leading-relaxed mb-4">GetAhead AI uses NextAuth (Auth.js) with short-lived, encrypted JWT sessions. This means:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li>Your session token is a signed, encrypted JWT stored in an HTTP-only cookie — not readable or decodable by JavaScript running in your browser.</li>
              <li>Sessions expire after about 15 minutes of inactivity, and refresh automatically while you're actively using the site.</li>
              <li>Session tokens are stored in HTTP-only, Secure, SameSite=Lax cookies — inaccessible to JavaScript.</li>
              <li>Signing out and changing your password are both designed to invalidate your other sessions immediately; in every case, a session stops working on its own within 15 minutes regardless.</li>
            </ul>
          </section>

          <hr className="border-rule" />

          <section id="section-7">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>7. Data Sharing</h2>
            <p className="text-ink leading-relaxed mb-4">We do not sell, rent, or trade your personal data. We share data only with the following trusted sub-processors, strictly as required to operate the service:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li><strong>Aiven Cloud</strong> — MySQL database hosting (data encrypted at rest, SOC 2 compliant).</li>
              <li><strong>Google Gemini API</strong> — AI evaluation and question generation (answer text sent per-request).</li>
              <li><strong>Resend</strong> — Transactional email delivery (password reset, support notifications, and internal operational alerts).</li>
              <li><strong>Vercel</strong> — Application hosting and deployment infrastructure.</li>
              <li><strong>Sentry</strong> — Server and client error tracking. Answer sheet content, OCR text, model responses, and request bodies are stripped before any error report is sent — Sentry only ever receives error messages, stack traces, and non-content metadata (e.g. which processing stage failed).</li>
            </ul>
            <p className="text-ink leading-relaxed mt-4">We may disclose data to law enforcement or regulatory authorities only when legally required to do so, and only to the minimum extent necessary.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>8. Data Retention</h2>
            <p className="text-ink leading-relaxed mb-4">We retain your data for as long as your account is active. Specifically:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li>Account data and evaluations are retained indefinitely while your account is active.</li>
              <li>When you delete your account (Settings → Security → Danger zone), all associated data (evaluations, reports, question papers, sessions) is permanently deleted immediately — well within our 7-day commitment.</li>
              <li>Audit logs are retained for 12 months, then automatically purged by a scheduled job.</li>
              <li>Error logs are retained for 30 days, then automatically purged by the same scheduled job.</li>
            </ul>
          </section>

          <hr className="border-rule" />

          <section id="section-9">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>9. Your Rights</h2>
            <p className="text-ink leading-relaxed mb-4">You have the following rights regarding your personal data:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li><strong>Access</strong> — Request a copy of the personal data we hold about you.</li>
              <li><strong>Correction</strong> — Request correction of inaccurate personal data.</li>
              <li><strong>Deletion</strong> — Request permanent deletion of your account and all associated data.</li>
              <li><strong>Portability</strong> — Request your evaluation data in a machine-readable format.</li>
              <li><strong>Objection</strong> — Object to specific processing of your data.</li>
            </ul>
            <p className="text-ink leading-relaxed mt-4">To exercise any of these rights, contact us via our <Link href="/contact" className="text-blue-600 hover:underline">Contact page</Link>. We will respond within 30 days.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-10">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>10. Data Security</h2>
            <p className="text-ink leading-relaxed mb-4">We implement the following security measures to protect your data:</p>
            <ul className="list-disc pl-6 space-y-2 text-ink">
              <li>All traffic encrypted via HTTPS/TLS (enforced in production)</li>
              <li>Passwords hashed with bcrypt (cost factor 12) — never stored in plaintext</li>
              <li>Short-lived JWT sessions (15 minutes) with server-side revocation on sign-out and password change</li>
              <li>HTTP-only, Secure, SameSite cookies to prevent XSS and CSRF</li>
              <li>Rate limiting on all authentication endpoints</li>
              <li>Security headers: Content-Security-Policy, X-Frame-Options, X-Content-Type-Options, Referrer-Policy</li>
              <li>Input validation on all API endpoints using Zod</li>
              <li>Role-based access control — data is isolated per user account</li>
              <li>Automated weekly dependency vulnerability scanning and update pull requests, plus a scan on every dependency change</li>
            </ul>
            <p className="text-ink leading-relaxed mt-4">Despite our best efforts, no system is perfectly secure. In the event of a data breach affecting your personal data, we will notify affected users within 72 hours via email.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-11">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>11. Children</h2>
            <p className="text-ink leading-relaxed">GetAhead AI is not directed at children under the age of 13. We do not knowingly collect personal data from children under 13. If you believe a child has provided us with personal data without parental consent, contact us via our <Link href="/contact" className="text-blue-600 hover:underline">Contact page</Link> and we will delete it promptly. For students aged 13–17, parental or guardian consent may be required depending on your jurisdiction.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>12. Changes to This Policy</h2>
            <p className="text-ink leading-relaxed">We may update this Privacy Policy from time to time. When we make significant changes, we will update the &quot;Effective date&quot; at the top of this page and notify registered users via email at least 14 days before the changes take effect. Your continued use of GetAhead AI after the effective date constitutes acceptance of the updated policy.</p>
          </section>

          <hr className="border-rule" />

          <section id="section-13">
            <h2 className="text-2xl font-bold text-gray-900 mb-4" style={{ fontFamily: "var(--font-display)" }}>13. Contact Us</h2>
            <p className="text-ink leading-relaxed mb-4">For any privacy-related questions, requests, or concerns:</p>
            <div className="bg-gray-50 rounded-2xl border border-rule p-6 space-y-2">
              <p className="text-ink"><strong>GetAhead AI</strong></p>
              <p className="text-ink">Privacy enquiries and general support: use our <Link href="/contact" className="text-blue-600 hover:underline">Contact page</Link> ({SITE_URL.replace(/^https?:\/\//, "")}/contact) — we don&apos;t currently support email.</p>
            </div>
          </section>

        </div>
      </article>

      {/* Breadcrumb */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 pb-8">
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm text-gray-400">
          <Link href="/" className="hover:text-graphite transition-colors">Home</Link>
          <ChevronRight className="w-4 h-4" />
          <span className="text-graphite">Privacy policy</span>
        </nav>
      </div>

      <SiteFooter />
    </div>
  );
}
